[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault"

[dependencies]
src3 = "0.8.0"
pausable = "0.26.1"
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
asset_interfaces = { path = "../../assets/interfaces" }