[project]
authors = ["ChartHouse Labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault"

[dependencies]
src20 = "0.8.0"
src3 = "0.8.0"
src5 = "0.8.0"
pausable = "0.26.1"
reentrancy = "0.26.1"
ownership = "0.26.1"
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
