[workspace]
members = [
    "contracts/mocks/fungible",
    "contracts/mocks/stork-mock",

    "contracts/core/pricefeed-wrapper",
    "contracts/core/vault",

    "contracts/testnet/token",
    "contracts/vault-expose",
]
